import type { DataTypeOption } from '@/types/settings'

// TODO 从后端获取
export const DataTypeOptions: DataTypeOption[] = [
  {
    labelCn: '心率',
    metricSymbol: ':FIELD_TYPE_HEART_RATE',
    value: 0,
    defaultValue: '82',
    icon: '\u0030',
    unit: 'bpm',
    label: 'Heart Rate',
    enLabel: { short: 'HR', medium: 'HeartRt', long: 'Heart Rate' },
  },
  {
    labelCn: '步数',
    metricSymbol: ':FIELD_TYPE_STEPS',
    value: 1,
    defaultValue: '12083',
    icon: '\u0031',
    unit: 'steps',
    label: 'Steps',
    enLabel: { short: 'Step', medium: 'Steps', long: 'Step Count' },
  },
  {
    labelCn: '卡路里',
    metricSymbol: ':FIELD_TYPE_CALORIES',
    value: 2,
    defaultValue: '1209',
    icon: '\u0032',
    unit: 'kcal',
    label: 'Calories',
    enLabel: { short: 'Cal', medium: 'Calories', long: 'Calories' },
  },
  {
    labelCn: '爬楼',
    metricSymbol: ':FIELD_TYPE_FLOORS_CLIMBED',
    value: 3,
    defaultValue: '10',
    icon: '\u0033',
    unit: 'floors',
    label: 'Floors Climbed',
    enLabel: { short: 'Flr', medium: 'Floors', long: 'Floor Climb' },
  },
  {
    labelCn: '海拔',
    metricSymbol: ':FIELD_TYPE_ALTITUDE',
    value: 4,
    defaultValue: '10',
    icon: '\u0034',
    unit: 'm',
    label: 'Altitude',
    enLabel: { short: 'Alt', medium: 'Altitude', long: 'Altitude' },
  },
  {
    labelCn: '今日距离',
    metricSymbol: ':FIELD_TYPE_DISTANCE',
    value: 5,
    defaultValue: '5.0',
    icon: '\u0045',
    unit: 'km',
    label: 'Distance',
    enLabel: { short: 'Dist', medium: 'Distance', long: 'Total Dist' },
  },
  {
    labelCn: '日出',
    metricSymbol: ':FIELD_TYPE_SUN_RISE',
    value: 7,
    defaultValue: '06:09',
    icon: '\u0060',
    unit: '',
    label: 'Sunrise',
    enLabel: { short: 'Rise', medium: 'Sunrise', long: 'Sunrise Time' },
  },
  {
    labelCn: '日落',
    metricSymbol: ':FIELD_TYPE_SUN_SET',
    value: 8,
    defaultValue: '18:12',
    icon: '\u0061',
    unit: '',
    label: 'Sunset',
    enLabel: { short: 'Set', medium: 'Sunset', long: 'Sunset Time' },
  },
  {
    labelCn: '设备电量',
    metricSymbol: ':FIELD_TYPE_BATTERY',
    value: 9,
    defaultValue: '100',
    icon: '\u0026',
    unit: '%',
    label: 'Battery',
    enLabel: { short: 'Bat', medium: 'Battery', long: 'Battery Lvl' },
  },
  {
    labelCn: '每日活动时间',
    metricSymbol: ':FIELD_TYPE_DAYLY_ACTIVE_MINUTES',
    value: 10,
    defaultValue: '30',
    icon: '\u0044',
    unit: 'min',
    label: 'Active Minutes (Daily)',
    enLabel: { short: 'ActM', medium: 'ActvMin', long: 'Daily Active' },
  },
  {
    labelCn: '每周活动时间',
    metricSymbol: ':FIELD_TYPE_WEEKLY_ACTIVE_MINUTES',
    value: 11,
    defaultValue: '150',
    icon: '\u0040',
    unit: 'min',
    label: 'Weekly Active Minutes',
    enLabel: { short: 'WkAc', medium: 'WkActive', long: 'Weekly Activ' },
  },
  {
    labelCn: '周跑步距离',
    metricSymbol: ':FIELD_TYPE_WEEKLY_RUN_DISTANCE',
    value: 12,
    defaultValue: '10',
    icon: '\u0046',
    unit: 'km',
    label: 'Weekly Run Distance',
    enLabel: { short: 'Run', medium: 'RunDist', long: 'Run Distance' },
  },
  {
    labelCn: '周骑行距离',
    metricSymbol: ':FIELD_TYPE_WEEKLY_CYCLING_DISTANCE',
    value: 13,
    defaultValue: '15',
    icon: '\u0047',
    unit: 'km',
    label: 'Weekly Cycling Distance',
    enLabel: { short: 'Cycle', medium: 'CycleDist', long: 'Cycle Dist' },
  },
  {
    labelCn: '恢复时间',
    metricSymbol: ':FIELD_TYPE_TIME_TO_RECOVERY',
    value: 14,
    defaultValue: '24',
    icon: '\u0041',
    unit: 'h',
    label: 'Recovery',
    enLabel: { short: 'Recv', medium: 'RecvTime', long: 'Recovery T' },
  },
  {
    labelCn: '身体电量',
    metricSymbol: ':FIELD_TYPE_BODY_BATTERY',
    value: 15,
    defaultValue: '50',
    icon: '\u0035',
    unit: '%',
    label: 'Body Battery',
    enLabel: { short: 'BBat', medium: 'BodyBatt', long: 'Body Batt' },
  },
  {
    labelCn: '血氧饱和度',
    metricSymbol: ':FIELD_TYPE_PULSE_OX',
    value: 16,
    defaultValue: '95',
    icon: '\u003b',
    unit: '%',
    label: 'PulseOx',
    enLabel: { short: 'SpO2', medium: 'Pulse Ox', long: 'Blood Oxygen Saturation' },
  },
  // {
  //   labelCn: '睡眠时间',
  //   metricSymbol: ':FIELD_TYPE_SLEEP_TIME',
  //   value: 17,
  //   defaultValue: '8',
  //   icon: '\u0021',
  //   label: 'Sleep (Daily)',
  //   enLabel: { short: 'Sleep', medium: 'Sleep Time', long: 'Total Sleep Hours' },
  // },
  // {
  //   labelCn: '压力',
  //   metricSymbol: ':FIELD_TYPE_STRESS',
  //   value: 18,
  //   defaultValue: '36',
  //   icon: '\u0036',
  //   unit: '',
  //   label: 'Stress',
  //   enLabel: { short: 'Strs', medium: 'Stress', long: 'Stress Lvl' },
  // },
  {
    labelCn: '通知',
    metricSymbol: ':FIELD_TYPE_NOTIFICATIONS',
    value: 19,
    defaultValue: '12',
    icon: '\u0025',
    unit: '',
    label: 'Notifications',
    enLabel: { short: 'Ntf', medium: 'Notif', long: 'Notif Cnt' },
  },
  // {
  //   labelCn: '闹钟',
  //   metricSymbol: ':FIELD_TYPE_ALARMS',
  //   value: 20,
  //   defaultValue: '3',
  //   icon: '\u0024',
  //   unit: '',
  //   label: 'Alarms',
  //   enLabel: { short: 'Alm', medium: 'Alarms', long: 'Alarm Cnt' },
  // },
  // {
  //   labelCn: '蓝牙连接状态',
  //   metricSymbol: ':INDICATOR_TYPE_BLUETOOTH',
  //   value: 21,
  //   defaultValue: '1',
  //   icon: '\u0022',
  //   unit: '',
  //   label: 'Bluetooth',
  //   enLabel: { short: 'BT', medium: 'Bluetooth', long: 'Bluetooth Connection' },
  // },
  {
    labelCn: '闹钟',
    metricSymbol: ':INDICATOR_TYPE_ALARM',
    value: 22,
    defaultValue: '1',
    icon: '\u0022',
    unit: '',
    label: 'Alarms',
    enLabel: { short: 'Alm', medium: 'Alarms', long: 'Alarm Cnt' },
  },
  {
    labelCn: '消息通知',
    metricSymbol: ':INDICATOR_TYPE_NOTIFICATIONS',
    value: 23,
    defaultValue: '1',
    icon: '\u0022',
    unit: '',
    label: 'Notifications',
    enLabel: { short: 'Ntf', medium: 'Notif', long: 'Notif Cnt' },
  },
  {
    labelCn: '呼吸频率',
    metricSymbol: ':FIELD_TYPE_RESPIRATION_RATE',
    value: 37,
    defaultValue: '16',
    icon: '\u0037',
    unit: 'brpm',
    label: 'Breaths per Min(if supported)',
    enLabel: { short: 'Resp', medium: 'RespRate', long: 'Resp Rate' },
  },
  {
    labelCn: '静息心率',
    metricSymbol: ':FIELD_TYPE_RESTING_HEARTRATE',
    value: 38,
    defaultValue: '70',
    icon: '\u0038',
    unit: 'bpm',
    label: 'Resting Heart Rate',
    enLabel: { short: 'RHR', medium: 'Rest HR', long: 'Resting Heart Rate' },
  },
  {
    labelCn: '周游泳距离',
    metricSymbol: ':FIELD_TYPE_WEEKLY_SWIMMING_DISTANCE',
    value: 39,
    defaultValue: '1',
    icon: '\u0048',
    unit: 'km',
    label: 'Weekly Swim Distance',
    enLabel: { short: 'Swim', medium: 'SwimDist', long: 'Swim Dist' },
  },
  {
    labelCn: '周步行距离',
    metricSymbol: ':FIELD_TYPE_WEEKLY_WALKING_DISTANCE',
    value: 40,
    defaultValue: '10',
    icon: '\u0049',
    unit: 'km',
    label: 'Weekly Walk Distance',
    enLabel: { short: 'Walk', medium: 'WalkDist', long: 'Walk Dist' },
  },
  {
    labelCn: 'VO2Max',
    metricSymbol: ':FIELD_TYPE_VO2_MAX',
    value: 57,
    defaultValue: '40',
    icon: '\u003a',
    unit: '',
    label: 'Vo2Max',
    enLabel: { short: 'VO2', medium: 'VO2 Max', long: 'Maximum Oxygen Uptake' },
  },
  {
    labelCn: '年',
    metricSymbol: ':FIELD_TYPE_DATE_YEAR',
    value: 70,
    defaultValue: '2023',
    icon: '\u0021',
    unit: '',
    label: 'Year',
    enLabel: { short: 'Year', medium: 'Year', long: 'Current Year' },
  },
  {
    labelCn: '月',
    metricSymbol: ':FIELD_TYPE_DATE_MONTH',
    value: 71,
    defaultValue: '10',
    icon: '\u0021',
    label: 'Month',
    enLabel: { short: 'Mo', medium: 'Month', long: 'Current Month' },
  },
  {
    labelCn: '日',
    metricSymbol: ':FIELD_TYPE_DATE_DAY',
    value: 72,
    defaultValue: '10',
    icon: '\u0021',
    label: 'Day',
    enLabel: { short: 'Day', medium: 'Day', long: 'Day of Month' },
  },
  {
    labelCn: '星期几',
    metricSymbol: ':FIELD_TYPE_DATE_WEEKDAY',
    value: 76,
    defaultValue: '1',
    icon: '\u0021',
    label: 'Weekday',
    enLabel: { short: 'Wkday', medium: 'Weekday', long: 'Day of Week' },
  },
  {
    labelCn: '第几周',
    metricSymbol: ':FIELD_TYPE_DATE_YEARWEEK',
    value: 77,
    defaultValue: '29',
    icon: '\u0021',
    label: 'Week of Year',
    enLabel: { short: 'Wk', medium: 'Week', long: 'Week of Year' },
  },
  // Goal items
  {
    labelCn: '目标设备电量',
    metricSymbol: ':GOAL_TYPE_BATTERY',
    value: 100,
    defaultValue: '80',
    icon: '\u0026',
    unit: '%',
    label: 'Battery (Hide Percentage)',
    enLabel: { short: 'Bat', medium: 'Battery', long: 'Battery Goal' },
  },
  {
    labelCn: '目标步数',
    metricSymbol: ':GOAL_TYPE_STEPS',
    value: 101,
    defaultValue: '8000',
    icon: '\u0031',
    unit: 'steps',
    label: 'Steps',
    enLabel: { short: 'GStp', medium: 'GoalStep', long: 'Step Goal' },
  },
  {
    labelCn: '目标卡路里',
    metricSymbol: ':GOAL_TYPE_CALORIES',
    value: 102,
    defaultValue: '500',
    icon: '\u0032',
    unit: 'kcal',
    label: 'Calories (Manual Goal)',
    enLabel: { short: 'GCal', medium: 'GoalCal', long: 'Calorie Goal' },
  },
  {
    labelCn: '目标爬楼',
    metricSymbol: ':GOAL_TYPE_FLOORS_CLIMBED',
    value: 103,
    defaultValue: '20',
    icon: '\u0033',
    unit: 'floors',
    label: 'Floors Climbed',
    enLabel: { short: 'Floor', medium: 'Floor', long: 'Floor Goal' },
  },
  {
    labelCn: '目标心率',
    metricSymbol: ':GOAL_TYPE_HEART_RATE',
    value: 104,
    defaultValue: '120',
    icon: '\u0030',
    unit: 'bpm',
    label: 'Heart Rate',
    enLabel: { short: 'HR', medium: 'HR', long: 'Heart Rate' },
  },
  {
    labelCn: '目标身体电量',
    metricSymbol: ':GOAL_TYPE_BODY_BATTERY',
    value: 111,
    defaultValue: '60',
    icon: '\u0035',
    unit: '%',
    label: 'Body Battery',
    enLabel: { short: 'BdBat', medium: 'BodyBat', long: 'Body Battery' },
  },
  {
    labelCn: '目标每日活动时间',
    metricSymbol: ':GOAL_TYPE_DAYLY_ACTIVE_MINUTES',
    value: 105,
    defaultValue: '60',
    icon: '\u0044',
    unit: 'min',
    label: 'Active Minutes (Daily)',
    enLabel: { short: 'GAct', medium: 'GoalAct', long: 'Daily Active' },
  },
  {
    labelCn: '目标每周活动时间',
    metricSymbol: ':GOAL_TYPE_WEEKLY_ACTIVE_MINUTES',
    value: 106,
    defaultValue: '300',
    icon: '\u0044',
    unit: 'min',
    label: 'Weekly Active Minutes',
    enLabel: { short: 'GWkA', medium: 'GoalWkAc', long: 'Weekly Activ' },
  },
  {
    labelCn: '周跑步目标距离',
    metricSymbol: ':GOAL_TYPE_WEEKLY_RUN_DISTANCE',
    value: 107,
    defaultValue: '20',
    icon: '\u0046',
    unit: 'km',
    label: 'Weekly Run Distance',
    enLabel: { short: 'GRD', medium: 'GoalRunDist', long: 'Run Distance' },
  },
  {
    labelCn: '周骑行目标距离',
    metricSymbol: ':GOAL_TYPE_WEEKLY_CYCLING_DISTANCE',
    value: 108,
    defaultValue: '30',
    icon: '\u0047',
    unit: 'km',
    label: 'Weekly Cycling Distance',
    enLabel: { short: 'GCD', medium: 'GoalCycleDist', long: 'Cycle Distance' },
  },
  {
    labelCn: '周游泳目标距离',
    metricSymbol: ':GOAL_TYPE_WEEKLY_SWIMMING_DISTANCE',
    value: 109,
    defaultValue: '2',
    icon: '\u0048',
    unit: 'km',
    label: 'Weekly Swim Distance',
    enLabel: { short: 'GSD', medium: 'SwimDist', long: 'Swim Distance' },
  },
  {
    labelCn: '周步行目标距离',
    metricSymbol: ':GOAL_TYPE_WEEKLY_WALKING_DISTANCE',
    value: 110,
    defaultValue: '20',
    icon: '\u0049',
    unit: 'km',
    label: 'Weekly Walk Distance',
    enLabel: { short: 'GWD', medium: 'WalkDist', long: 'Walk Distance' },
  },
  {
    labelCn: '秒针',
    metricSymbol: ':GOAL_TYPE_SECOND_OF_MINUTE',
    value: 120,
    defaultValue: '40',
    icon: '\u0021',
    unit: '',
    label: 'Second',
    enLabel: { short: 'Sec', medium: 'Second', long: 'Second' },
  },
  // Chart items
  {
    labelCn: '7天步数',
    metricSymbol: ':CHART_TYPE_7DAYS_STEPS',
    value: 150,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'steps',
    label: '7 Days Steps',
    enLabel: { short: '7 Days Steps', medium: '7 Days Steps', long: '7 Days Steps' },
  },
  {
    labelCn: '7天活动分钟',
    metricSymbol: ':CHART_TYPE_7DAYS_ACTIVE_MINUTES',
    value: 151,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'min',
    label: '7 Days Active Minutes',
    enLabel: { short: '7 Days Active Minutes', medium: '7 Days Active Minutes', long: '7 Days Active Minutes' },
  },
  {
    labelCn: '7天爬楼',
    metricSymbol: ':CHART_TYPE_7DAYS_FLOORS_CLIMBED',
    value: 152,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'floors',
    label: '7 Days Floors Climbed',
    enLabel: { short: '7 Days Floors Climbed', medium: '7 Days Floors Climbed', long: '7 Days Floors Climbed' },
  },
  {
    labelCn: '7天卡路里',
    metricSymbol: ':CHART_TYPE_7DAYS_CALORIES',
    value: 153,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'kcal',
    label: '7 Days Calories',
    enLabel: { short: '7 Days Calories', medium: '7 Days Calories', long: '7 Days Calories' },
  },
  {
    labelCn: '7天距离',
    metricSymbol: ':CHART_TYPE_7DAYS_DISTANCE',
    value: 154,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'km',
    label: '7 Days Distance',
    enLabel: { short: '7 Days Calories', medium: '7 Days Calories', long: '7 Days Calories' },
  },
  {
    labelCn: '7天轮椅',
    metricSymbol: ':CHART_TYPE_7DAYS_PUSH',
    value: 155,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'km',
    label: '7 Days Wheelchair Distance',
    enLabel: { short: '7 Days Wheelchair Distance', medium: '7 Days Wheelchair Distance', long: '7 Days Wheelchair Distance' },
  },
  {
    labelCn: '7天轮椅距离',
    metricSymbol: ':CHART_TYPE_7DAYS_PUSH_DISTANCE',
    value: 156,
    defaultValue: '10000',
    icon: '\u0021',
    unit: 'km',
    label: '7 Days Push Distance',
    enLabel: { short: '7 Days Push Distance', medium: '7 Days Push Distance', long: '7 Days Push Distance' },
  },
  // Weather & environment
  // {
  //   labelCn: '天气描述',
  //   metricSymbol: ':FIELD_TYPE_WEATHER_DESCRIPTION',
  //   value: 36,
  //   defaultValue: 'Sunny',
  //   icon: '\u0021',
  //   unit: '',
  //   label: 'Weather Desc',
  //   enLabel: { short: 'WDesc', medium: 'WeatherDesc', long: 'Weather Description' },
  // },
  {
    labelCn: '天气',
    metricSymbol: ':FIELD_TYPE_WEATHER',
    value: 30,
    defaultValue: '25',
    icon: '\u0021',
    unit: '°C',
    label: 'Weather',
    enLabel: { short: 'Weath', medium: 'Weather', long: 'Weather' },
  },
  {
    labelCn: '湿度',
    metricSymbol: ':FIELD_TYPE_WEATHER_HUMIDITY',
    value: 33,
    defaultValue: '60',
    icon: '\u0021',
    unit: '%',
    label: 'Humidity',
    enLabel: { short: 'Hum', medium: 'Humidity', long: 'Humidity' },
  },
  {
    labelCn: '云量',
    metricSymbol: ':FIELD_TYPE_WEATHER_CLOUDS',
    value: 54,
    defaultValue: '40',
    icon: '\u0021',
    unit: '%',
    label: 'Clouds',
    enLabel: { short: 'Cloud', medium: 'Clouds', long: 'Cloud Coverage' },
  },
  {
    labelCn: '风速',
    metricSymbol: ':FIELD_TYPE_WEATHER_WIND_SPEED',
    value: 34,
    defaultValue: '5',
    icon: '\u0021',
    unit: 'm/s',
    label: 'Wind Speed',
    enLabel: { short: 'Wind', medium: 'WindSpd', long: 'Wind Speed' },
  },
  // {
  //   labelCn: '风向',
  //   metricSymbol: ':FIELD_TYPE_WEATHER_WIND_DIRECTION',
  //   value: 44,
  //   defaultValue: '90',
  //   icon: '\u0021',
  //   unit: '°',
  //   label: 'Wind Dir',
  //   enLabel: { short: 'WDir', medium: 'WindDir', long: 'Wind Direction' },
  // },
  {
    labelCn: '温度',
    metricSymbol: ':FIELD_TYPE_TEMPERATURE',
    value: 31,
    defaultValue: '25',
    icon: '\u0021',
    unit: '°C',
    label: 'Temperature',
    enLabel: { short: 'Temp', medium: 'Temp', long: 'Temperature' },
  },
  // {
  //   labelCn: '最高温度',
  //   metricSymbol: ':FIELD_TYPE_TEMPERATURE_HIGH',
  //   value: 41,
  //   defaultValue: '30',
  //   icon: '\u0021',
  //   unit: '°C',
  //   label: 'High Temp',
  //   enLabel: { short: 'Hi', medium: 'HiTemp', long: 'High Temperature' },
  // },
  // {
  //   labelCn: '最低温度',
  //   metricSymbol: ':FIELD_TYPE_TEMPERATURE_LOW',
  //   value: 42,
  //   defaultValue: '18',
  //   icon: '\u0021',
  //   unit: '°C',
  //   label: 'Low Temp',
  //   enLabel: { short: 'Lo', medium: 'LoTemp', long: 'Low Temperature' },
  // },
  {
    labelCn: '位置',
    metricSymbol: ':FIELD_TYPE_LOCATION',
    value: 58,
    defaultValue: 'City',
    icon: '\u0021',
    unit: '',
    label: 'Location',
    enLabel: { short: 'Loc', medium: 'Location', long: 'Location' },
  },
  {
    labelCn: '经纬度',
    metricSymbol: ':FIELD_TYPE_POSITION',
    value: 56,
    defaultValue: '0,0',
    icon: '\u0021',
    unit: '',
    label: 'Position',
    enLabel: { short: 'Pos', medium: 'Position', long: 'GPS Position' },
  },
  {
    labelCn: '空气质量指数',
    metricSymbol: ':FIELD_TYPE_AQI',
    value: 59,
    defaultValue: '50',
    icon: '\u0021',
    unit: '',
    label: 'AQI',
    enLabel: { short: 'AQI', medium: 'AQI', long: 'Air Quality Index' },
  },
  {
    labelCn: 'PM2.5',
    metricSymbol: ':FIELD_TYPE_AQI_PM25',
    value: 60,
    defaultValue: '35',
    icon: '\u0021',
    unit: 'µg/m³',
    label: 'PM2.5',
    enLabel: { short: 'PM2.5', medium: 'PM2.5', long: 'PM2.5' },
  },
  // {
  //   labelCn: 'PM10',
  //   metricSymbol: ':FIELD_TYPE_AQI_PM10',
  //   value: 61,
  //   defaultValue: '40',
  //   icon: '\u0021',
  //   unit: 'µg/m³',
  //   label: 'PM10',
  //   enLabel: { short: 'PM10', medium: 'PM10', long: 'PM10' },
  // },
  // {
  //   labelCn: '臭氧 O₃',
  //   metricSymbol: ':FIELD_TYPE_AQI_O3',
  //   value: 62,
  //   defaultValue: '80',
  //   icon: '\u0021',
  //   unit: 'µg/m³',
  //   label: 'O3',
  //   enLabel: { short: 'O3', medium: 'Ozone', long: 'Ozone (O3)' },
  // },
  // {
  //   labelCn: '二氧化氮 NO₂',
  //   metricSymbol: ':FIELD_TYPE_AQI_NO2',
  //   value: 63,
  //   defaultValue: '40',
  //   icon: '\u0021',
  //   unit: 'µg/m³',
  //   label: 'NO2',
  //   enLabel: { short: 'NO2', medium: 'NitroDiox', long: 'Nitrogen Dioxide (NO2)' },
  // },
  // {
  //   labelCn: '二氧化硫 SO₂',
  //   metricSymbol: ':FIELD_TYPE_AQI_SO2',
  //   value: 64,
  //   defaultValue: '20',
  //   icon: '\u0021',
  //   unit: 'µg/m³',
  //   label: 'SO2',
  //   enLabel: { short: 'SO2', medium: 'SulfurDiox', long: 'Sulfur Dioxide (SO2)' },
  // },
  // {
  //   labelCn: '一氧化碳 CO',
  //   metricSymbol: ':FIELD_TYPE_AQI_CO',
  //   value: 65,
  //   defaultValue: '1',
  //   icon: '\u0021',
  //   unit: 'mg/m³',
  //   label: 'CO',
  //   enLabel: { short: 'CO', medium: 'CarbonMon', long: 'Carbon Monoxide (CO)' },
  // },
  // {
  //   labelCn: '氨气 NH₃',
  //   metricSymbol: ':FIELD_TYPE_AQI_NH3',
  //   value: 66,
  //   defaultValue: '1',
  //   icon: '\u0021',
  //   unit: 'µg/m³',
  //   label: 'NH3',
  //   enLabel: { short: 'NH3', medium: 'Ammonia', long: 'Ammonia (NH3)' },
  // },
  {
    labelCn: '一年中的第几天',
    metricSymbol: ':FIELD_TYPE_DATE_YEARDAY',
    value: 78,
    defaultValue: '200',
    icon: '\u0021',
    unit: '',
    label: 'Day of Year',
    enLabel: { short: 'DoY', medium: 'DayYear', long: 'Day of Year' },
  },
]
