import type { OptionFormat } from '@/types/settings'

export enum DateFormatConstants {
  DD = 0,
  DDD = 1,
  DDDD = 2,
  DO = 3,
  MMM = 4,
  MMMM = 5,
  MMM_D = 6,
  MMMM_D = 7,
  DDD_DD = 8,
  MMM_D_DDD = 9,
  MMM_D_DDDD = 10,
  MMMM_D_DDDD = 11,
  DDDD_MMMM_D = 12,
  MMM_D_YYYY = 13,
  D_MMM_YYYY = 14,
  DD_MM_YYYY = 15,
  MM_DD_YYYY = 16,
  YYYY_MM_DD = 17,
  MMMM_DO_YYYY = 18,
  MMM_D_YYYY_DDDD = 19,
  LUNAR_DATE = 20,
  GANZHI_YEAR = 21,
  ZODIAC_YEAR = 22,
  FESTIVAL_OR_SOLAR_TERM = 23,
  HUANGLI_YI = 24,
  HUANGLI_JI = 25,
  LUNAR_SHICHEN = 26,
  CHINESE_WEEKDAY_SHORT = 27,
  CHINESE_WEEKDAY_LONG = 28,
  WEEKDAY_LONG = 29,
  MONTH_LONG = 30,
  MM_DD = 31,
  MM_DD_SLASH = 32,
  SOLAR_YEAR_LABEL = 33,
  SOLAR_MONTH_LABEL = 34,
  SOLAR_MONTH_ZH = 35,
  SOLAR_DAY_LABEL = 36,
  SOLAR_DAY_ZH = 37,
  SOLAR_MONTH_DAY = 38,
  SOLAR_MONTH_DAY_ZH = 39,
  LUNAR_YEAR = 40,
  LUNAR_MONTH = 41,
  LUNAR_DAY = 42,
  LUNAR_MONTH_PREFIX = 43,
  NEXT_GREGORIAN_FESTIVAL = 48,
  NEXT_SOLAR_TERM = 50,
  ZODIAC = 51,
  SHICHEN_BRANCH = 52,
  FOUR_PILLAR_YEAR = 53,
  FOUR_PILLAR_MONTH = 54,
  FOUR_PILLAR_DAY = 55,
  FOUR_PILLAR_HOUR = 56,
  YEAR = 57,
}

export const DateFormatOptions: OptionFormat<number>[] = [
  { value: DateFormatConstants.DD, label: 'DD', example: '05' },
  { value: DateFormatConstants.DDD, label: 'ddd', example: 'Mon' },
  { value: DateFormatConstants.DDDD, label: 'dd', example: 'Mo' },
  { value: DateFormatConstants.DO, label: 'Do', example: '5th' },
  { value: DateFormatConstants.MMM, label: 'MMM', example: 'Sep' },
  { value: DateFormatConstants.MMMM, label: 'MM', example: '09' },
  { value: DateFormatConstants.MMM_D, label: 'MMM D', example: 'Sep 5' },
  { value: DateFormatConstants.MMMM_D, label: 'M/D', example: '9/5' },
  { value: DateFormatConstants.DDD_DD, label: 'ddd DD', example: 'Mon 05' },
  { value: DateFormatConstants.MMM_D_DDD, label: 'MMM D, ddd', example: 'Sep 5, Mon' },
  { value: DateFormatConstants.MMM_D_DDDD, label: 'MMM DD, ddd', example: 'Sep 05, Mon' },
  { value: DateFormatConstants.MMMM_D_DDDD, label: 'MMM, D ddd', example: 'Sep, 5 Mon' },
  { value: DateFormatConstants.DDDD_MMMM_D, label: 'ddd MMM D', example: 'Mon Sep 5' },
  { value: DateFormatConstants.MMM_D_YYYY, label: 'MMM D, YYYY', example: 'Sep 5, 2023' },
  { value: DateFormatConstants.D_MMM_YYYY, label: 'D MMM YYYY', example: '5 Sep 2023' },
  { value: DateFormatConstants.DD_MM_YYYY, label: 'DD.MM.YYYY', example: '05.09.2023' },
  { value: DateFormatConstants.MM_DD_YYYY, label: 'MM/DD/YYYY', example: '09/05/2023' },
  { value: DateFormatConstants.YYYY_MM_DD, label: 'YYYY-MM-DD', example: '2023-09-05' },
  { value: DateFormatConstants.MMMM_DO_YYYY, label: 'MMM Do, YYYY', example: 'Sep 5th, 2023' },
  { value: DateFormatConstants.MMM_D_YYYY_DDDD, label: 'MMM D, YYYY, ddd', example: 'Sep 5, 2023, Mon' },
  { value: DateFormatConstants.LUNAR_DATE, label: 'Lunar date', zhsLabel: '农历日期', example: '五月十五' },
  { value: DateFormatConstants.GANZHI_YEAR, label: 'Ganzhi year', zhsLabel: '干支年', example: '乙巳' },
  { value: DateFormatConstants.ZODIAC_YEAR, label: 'Zodiac year', zhsLabel: '生肖年', example: '蛇年' },
  { value: DateFormatConstants.FESTIVAL_OR_SOLAR_TERM, label: 'Festival / solar term', zhsLabel: '节日节气', example: '中秋节' },
  { value: DateFormatConstants.HUANGLI_YI, label: 'Huangli suitable', zhsLabel: '黄历宜', example: '宜 出行' },
  { value: DateFormatConstants.HUANGLI_JI, label: 'Huangli avoid', zhsLabel: '黄历忌', example: '忌 动土' },
  { value: DateFormatConstants.LUNAR_SHICHEN, label: 'Lunar shichen', zhsLabel: '农历时辰', example: '午时' },
  { value: DateFormatConstants.CHINESE_WEEKDAY_SHORT, label: 'Chinese weekday short', zhsLabel: '中文星期短', example: '周一' },
  { value: DateFormatConstants.CHINESE_WEEKDAY_LONG, label: 'Chinese weekday long', zhsLabel: '中文星期长', example: '星期一' },
  { value: DateFormatConstants.WEEKDAY_LONG, label: 'dddd', zhsLabel: '完整星期', example: 'Monday' },
  { value: DateFormatConstants.MONTH_LONG, label: 'MMMM', zhsLabel: '完整月份', example: 'September' },
  { value: DateFormatConstants.MM_DD, label: 'MM-DD', example: '05-25' },
  { value: DateFormatConstants.MM_DD_SLASH, label: 'MM/DD', example: '05/25' },
  { value: DateFormatConstants.SOLAR_YEAR_LABEL, label: 'Gregorian year', zhsLabel: '公历年', example: '2026年' },
  { value: DateFormatConstants.SOLAR_MONTH_LABEL, label: 'Gregorian month', zhsLabel: '公历月（数字）', example: '8月' },
  { value: DateFormatConstants.SOLAR_MONTH_ZH, label: 'Chinese month', zhsLabel: '公历月（中文）', example: '八月' },
  { value: DateFormatConstants.SOLAR_DAY_LABEL, label: 'Gregorian day', zhsLabel: '公历日（数字）', example: '16日' },
  { value: DateFormatConstants.SOLAR_DAY_ZH, label: 'Chinese day', zhsLabel: '公历日（中文）', example: '十六日' },
  { value: DateFormatConstants.SOLAR_MONTH_DAY, label: 'Gregorian month and day', zhsLabel: '公历月日', example: '8月16日' },
  { value: DateFormatConstants.SOLAR_MONTH_DAY_ZH, label: 'Chinese month and day', zhsLabel: '公历中文月日', example: '八月十六日' },
  { value: DateFormatConstants.LUNAR_YEAR, label: 'Lunar year', zhsLabel: '农历年', example: '二〇二六年' },
  { value: DateFormatConstants.LUNAR_MONTH, label: 'Lunar month', zhsLabel: '农历月', example: '七月' },
  { value: DateFormatConstants.LUNAR_DAY, label: 'Lunar day', zhsLabel: '农历日', example: '初四' },
  { value: DateFormatConstants.LUNAR_MONTH_PREFIX, label: 'Prefixed lunar month', zhsLabel: '带前缀农历月', example: '农历七月' },
  { value: DateFormatConstants.NEXT_GREGORIAN_FESTIVAL, label: 'Next Gregorian festival', zhsLabel: '下一个公历节日', example: '国庆节+10' },
  { value: DateFormatConstants.NEXT_SOLAR_TERM, label: 'Next solar term', zhsLabel: '下一个节气', example: '处暑+6' },
  { value: DateFormatConstants.ZODIAC, label: 'Zodiac', zhsLabel: '生肖', example: '马' },
  { value: DateFormatConstants.SHICHEN_BRANCH, label: 'Shichen branch', zhsLabel: '时支', example: '申' },
  { value: DateFormatConstants.FOUR_PILLAR_YEAR, label: 'Year pillar', zhsLabel: '年柱', example: '丙午' },
  { value: DateFormatConstants.FOUR_PILLAR_MONTH, label: 'Month pillar', zhsLabel: '月柱', example: '丙申' },
  { value: DateFormatConstants.FOUR_PILLAR_DAY, label: 'Day pillar', zhsLabel: '日柱', example: '壬戌' },
  { value: DateFormatConstants.FOUR_PILLAR_HOUR, label: 'Hour pillar', zhsLabel: '时柱', example: '戊申' },
  { value: DateFormatConstants.YEAR, label: 'YYYY', example: '2026' },
]
