import type { OptionFormat } from '@/types/settings'

export enum DateFormatConstants {
  DD = 0,
  DDD = 1,
  DDDD = 2,
  DO = 3,
  MMM = 4,
  MMMM = 5,
  MMM_D = 6,
  MMMM_D = 7,
  DDD_DD = 8,
  MMM_D_DDD = 9,
  MMM_D_DDDD = 10,
  MMMM_D_DDDD = 11,
  DDDD_MMMM_D = 12,
  MMM_D_YYYY = 13,
  D_MMM_YYYY = 14,
  DD_MM_YYYY = 15,
  MM_DD_YYYY = 16,
  YYYY_MM_DD = 17,
  MMMM_DO_YYYY = 18,
  MMM_D_YYYY_DDDD = 19,
}

export const DateFormatOptions: OptionFormat<number>[] = [
  { value: DateFormatConstants.DD, label: 'DD', example: '05' },
  { value: DateFormatConstants.DDD, label: 'ddd', example: 'Mon' },
  { value: DateFormatConstants.DDDD, label: 'dddd', example: 'Monday' },
  { value: DateFormatConstants.DO, label: 'Do', example: '5th' },
  { value: DateFormatConstants.MMM, label: 'MMM', example: 'Sep' },
  { value: DateFormatConstants.MMMM, label: 'MMMM', example: 'September' },
  { value: DateFormatConstants.MMM_D, label: 'MMM D', example: 'Sep 5' },
  { value: DateFormatConstants.MMMM_D, label: 'MMMM D', example: 'September 5' },
  { value: DateFormatConstants.DDD_DD, label: 'ddd DD', example: 'Mon 05' },
  { value: DateFormatConstants.MMM_D_DDD, label: 'MMM D, ddd', example: 'Sep 5, Mon' },
  { value: DateFormatConstants.MMM_D_DDDD, label: 'MMM D, dddd', example: 'Sep 5, Monday' },
  { value: DateFormatConstants.MMMM_D_DDDD, label: 'MMMM, D dddd', example: 'September, 5 Monday' },
  { value: DateFormatConstants.DDDD_MMMM_D, label: 'dddd, MMMM D', example: 'Monday, September 5' },
  { value: DateFormatConstants.MMM_D_YYYY, label: 'MMM D, YYYY', example: 'Sep 5, 2023' },
  { value: DateFormatConstants.D_MMM_YYYY, label: 'D MMM YYYY', example: '5 Sep 2023' },
  { value: DateFormatConstants.DD_MM_YYYY, label: 'DD.MM.YYYY', example: '05.09.2023' },
  { value: DateFormatConstants.MM_DD_YYYY, label: 'MM/DD/YYYY', example: '09/05/2023' },
  { value: DateFormatConstants.YYYY_MM_DD, label: 'YYYY-MM-DD', example: '2023-09-05' },
  { value: DateFormatConstants.MMMM_DO_YYYY, label: 'MMMM Do, YYYY', example: 'September 5th, 2023' },
  { value: DateFormatConstants.MMM_D_YYYY_DDDD, label: 'MMM D, YYYY, dddd', example: 'Sep 5, 2023, Monday' },
]
